version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    container_name: mswi_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/microservice
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/posgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: postgres_db
